### ISSUE TITLE
Generated code for Hubspot form is using '&quot;' instead of normal double quotes.

### ISSUE THREAD

**Issue by avree** [reatlat/eleventy-plugin-hubspot#2]
Hi,

The generated code is using `&quot;` characters, which causes the form to not load and a javascript error in console - these should be normal `"` characters, I think. Thanks for any help/advice!

**Comment by reatlat** [comment]
@avree would you please provide a code example, how you use it? so I can reproduce error on my end.

***Note*** you can change private information like your `portal_id` and `form_id`

**Comment by avree** [comment]
Thanks for the reply! I was able to pinpoint the source of the issue, which was my usage of the Hubspot form shortcode within a `.md` file, rather than an `.njk` one, which causes an issue when Eleventy processes the Markdown prior to applying the template engine.

I'm experimenting with markdown-it-shortcode-tag, a package that seems to solve the shortcode in .md issue, except that it is currently replacing the normal double quotes with curly double quotes (which is a step up from the &quot; of before.)

 I'll report back if I find a better package or other solution for the issue.

**Comment by reatlat** [comment]
@avree TY, I didn't test it with markdown, will try to replicate you issue, and fix bug ASAP

**Comment by avree** [comment]
@reatlat I was able to fix it for now, made a PR with my code. Only side-effect is that the form appears below the meeting in your demo due to being triggered after load.

**Comment by avree** [comment]
@reatlat Thanks for merging! do you mind bumping version so I can go back to using your NPM-published package? I didn't want to mess with your versioning in my PR.
